version: '2.24.5'

services:
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=oier
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - 5050:80

#Contenedores para servicios de MySQL
  # mysql:
  #   image: mysql/mysql-server:latest
  #   environment:
  #     - MYSQL_DB=my_store
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_PORT=3306
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80

volumes:
  postgres_volume:
